import type { Finding, RiskCard, Severity } from "./types.js";

const SEVERITY_ORDER: Severity[] = ["critical", "high", "medium", "info"];

function sortFindings(findings: Finding[]): Finding[] {
  return [...findings].sort((a, b) => {
    const ds =
      SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity);
    if (ds !== 0) return ds;
    return (a.path ?? "").localeCompare(b.path ?? "");
  });
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

/** Render a markdown PR risk card (deterministic, no LLM). */
export function renderMarkdownCard(card: RiskCard): string {
  const lines: string[] = [];
  lines.push("# PR Risk Card");
  lines.push("");
  lines.push(
    `**overall risk:** **${card.riskLevel}** · score \`${card.score}\` · generated \`${card.generatedAt}\``,
  );
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`| --- | ---: |`);
  lines.push(`| Files changed | ${card.summary.filesChanged} |`);
  lines.push(`| Lines added | ${card.summary.totalAdded} |`);
  lines.push(`| Lines removed | ${card.summary.totalRemoved} |`);
  lines.push(`| Findings | ${card.summary.findingCount} |`);
  lines.push("");

  lines.push("## Findings");
  lines.push("");
  if (card.findings.length === 0) {
    lines.push("_No path, size, or secret-like findings._");
    lines.push("");
  } else {
    lines.push("| Severity | Rule | Path | Message |");
    lines.push("| --- | --- | --- | --- |");
    for (const f of sortFindings(card.findings)) {
      lines.push(
        `| ${f.severity} | \`${f.id}\` | ${escapeCell(f.path ?? "—")} | ${escapeCell(f.message)} |`,
      );
    }
    lines.push("");
    const withHint = sortFindings(card.findings).filter((f) => f.lineHint);
    if (withHint.length > 0) {
      lines.push("### Evidence (redacted snippets)");
      lines.push("");
      for (const f of withHint) {
        lines.push(`- **${f.severity}** \`${f.path}\`: \`${escapeCell(f.lineHint!)}\``);
      }
      lines.push("");
    }
  }

  lines.push("## Changed files");
  lines.push("");
  if (card.files.length === 0) {
    lines.push("_Empty diff._");
    lines.push("");
  } else {
    lines.push("| Path | Status | + | − | Binary |");
    lines.push("| --- | --- | ---: | ---: | --- |");
    for (const f of card.files) {
      lines.push(
        `| ${escapeCell(f.path)} | ${f.status} | ${f.added} | ${f.removed} | ${f.isBinary ? "yes" : "no"} |`,
      );
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(
    "_Generated by **pr-risk-card** (deterministic rules only — not a substitute for human review or a full secrets scanner)._",
  );
  lines.push("");
  return lines.join("\n");
}

export function renderOneLineSummary(card: RiskCard): string {
  return `pr-risk-card: risk=${card.riskLevel} score=${card.score} findings=${card.summary.findingCount} files=${card.summary.filesChanged} +${card.summary.totalAdded}/-${card.summary.totalRemoved}`;
}
